apps/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('schedules/', views.schedules, name='schedules'),
    path('attendants/', views.attendants, name='attendants'),
    
    # events
    path('events/', views.events, name='events'),
    path('events/get/', views.get_events, name='get_events'),
    path('events/comment/<slug:slug>/', views.post_comment, name='post-comment'),
    path('events/create', views.create_event, name='create-event'),
    path('events/register', views.register_event, name='register-event'),
    path('events/update/<slug:slug>/', views.update_event, name='update-event'),
    path('events/delete/<slug:slug>/', views.delete_event, name='delete-event'),
    path('events/<slug:slug>/', views.event, name='event'),
    
    # venues
    path('venues/', views.venues, name='venues'),
    path('venues/create', views.create_venue, name='create-venue'),
    path('venues/update/<slug:slug>/', views.update_venue, name='update-venue'),
    path('venues/delete/<slug:slug>/', views.delete_venue, name='delete-venue'),
    path('venues/<slug:slug>/', views.venue, name='venue'),
    
    # venues
    path('jobs/', views.jobs, name='jobs'),
    path('jobs/create', views.create_job, name='create-job'),
    
    # forums
    path('forums/', views.forums, name='forums'),
    path('forums/comment/<slug:slug>/', views.forum_comment, name='forum-comment'),
    path('forums/create', views.create_forum, name='create-forum'),
    path('forums/update/<slug:slug>/', views.update_forum, name='update-forum'),
    path('forums/delete/<slug:slug>/', views.delete_forum, name='delete-forum'),
    path('forums/<slug:slug>/', views.forum, name='forum'),
    
    # speakers
    path('speakers/', views.speakers, name='speakers'),
    path('speakers/create', views.create_speaker, name='create-speaker'),
    path('speakers/update/<slug:slug>/', views.update_speaker, name='update-speaker'),
    path('speakers/delete/<slug:slug>/', views.delete_speaker, name='delete-speaker'),
    
    path('calendar/', views.calendar, name='calendar'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    
    # checkout
    path('checkout/', views.payment_checkout, name='checkout_payment'),
    # path('create_payment/', views.create_payment, name='create_payment'),
    path('execute_payment/', views.execute_payment, name='execute_payment'),
    path('execute_payment/failed', views.payment_failed, name='payment_failed'),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path('', include('apps.users.urls')),
    path('', include("django.contrib.auth.urls")),
    path('paypal/', include("paypal.standard.ipn.urls")),
    path('admin/', admin.site.urls),
]

# Serve static and media files
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]
urlpatterns += [
    re_path(r'^static/(?P<path>.*)$', serve, {
        'document_root': settings.STATIC_ROOT,
    }),
]

# admin.site.enable_nav_sidebar = False 
admin.site.site_header = "University Alumni Dashboard"
admin.site.site_title = "University Alumni Portal"
# admin.site.index_title = "EMS | Dashboard"

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" bd-theme="bd-theme-light" style="--clr-theme-1: #f87a58" lang="zxx">
  <!-- Mirrored from codeskdhaka.com/html/expovent-prev/expovent/{% url 'users:home' %} by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 17 Mar 2024 11:53:39 GMT -->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{% if title %}{{ title }}{% else %}University Alumni Website{% endif %}</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-style-mode" content="1" />
    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />
    {% block core_css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'css/metisMenu.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/slick.css' %}" />
    <link rel="stylesheet" href="{% static 'css/backtotop.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flaticon_expovent.css' %}" />
    <link rel="stylesheet" href="{% static 'css/fontawesome-pro.css' %}" />
    <link rel="stylesheet" href="{% static 'css/spacing.css' %}" />
    <link rel="stylesheet" href="{% static 'css/notifications.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}?{% now 'U' %}" />
    {% endblock %} {% block page_css %} {% endblock %}
  </head>

  <body class="body-area">
    <!-- Preloder start -->
    <div id="preloader">
      <div class="sk-three-bounce">
        <div class="sk-child sk-bounce1"></div>
        <div class="sk-child sk-bounce2"></div>
        <div class="sk-child sk-bounce3"></div>
      </div>
    </div>
    <!-- Preloder start -->

    <!-- Offcanvas area start -->
    <div class="fix">
      <div class="offcanvas__info">
        <div class="offcanvas__wrapper">
          <div class="offcanvas__content">
            <div class="offcanvas__top mb-40 d-flex justify-content-between align-items-center">
              <div class="offcanvas__logo">
                <a href="{% url 'users:home' %}">
                  <img src="{% static 'img/logo/logo-black.png' %}" alt="logo not found" />
                </a>
              </div>
              <div class="offcanvas__close">
                <button>
                  <i class="fal fa-times"></i>
                </button>
              </div>
            </div>
            <div class="offcanvas__search mb-25">
              <form action="{% url 'users:events' %}">
                <label for="search">Search: </label>
                <input type="text" name="query" placeholder="What are you searching for?" id="search"/>
                <button type="submit"><i class="far fa-search"></i></button>
              </form>
            </div>
            <div class="mobile-menu fix mb-40"></div>
            <div class="offcanvas__contact mt-30 mb-20">
              <h4>Contact Info</h4>
              <ul>
                <li class="d-flex align-items-center">
                  <div class="offcanvas__contact-icon mr-15">
                    <i class="fal fa-map-marker-alt"></i>
                  </div>
                  <div class="offcanvas__contact-text">
                    <a target="_blank" href="https://www.google.com/maps/place/Dhaka/@23.7806207,90.3492859,12z/data=!3m1!4b1!4m5!3m4!1s0x3755b8b087026b81:0x8fa563bbdd5904c2!8m2!3d23.8104753!4d90.4119873">12/A, Mirnada City Tower, NYC</a>
                  </div>
                </li>
                <li class="d-flex align-items-center">
                  <div class="offcanvas__contact-icon mr-15">
                    <i class="far fa-phone"></i>
                  </div>
                  <div class="offcanvas__contact-text">
                    <a href="tel:+088889797697">+088889797697</a>
                  </div>
                </li>
                <li class="d-flex align-items-center">
                  <div class="offcanvas__contact-icon mr-15">
                    <i class="fal fa-envelope"></i>
                  </div>
                  <div class="offcanvas__contact-text">
                    <a href="tel:+012-345-6789"><span class="mailto:support@mail.com">support@mail.com</span></a>
                  </div>
                </li>
              </ul>
            </div>
            <div class="offcanvas__social">
              <ul>
                <li>
                  <a href="#"><i class="fab fa-facebook-f"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fab fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fab fa-youtube"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fab fa-linkedin"></i></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="offcanvas__overlay"></div>
    <div class="offcanvas__overlay-white"></div>
    <!-- Offcanvas area start -->

    <!-- Dashboard area start -->
    <div class="page__full-wrapper">
      <!-- App sidebar area start -->
      {% block sidebar %} {% include 'includes/sidebar.html' %}
      <div class="app__offcanvas-overlay"></div>
      {% endblock %}

      <div class="page__body-wrapper">
        {% block navbar %} {% include 'includes/navbar.html' %}
        <div class="body__overlay"></div>        
        {% endblock %} {% block content %} {% endblock %}
      </div>
    </div>

    <div class="notifications"></div>

    {% block progress_btn %}
    <div class="progress-wrap d-none">
      <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
      </svg>
    </div>

    {% endblock %} {% block core_js %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/apexcharts.min.js' %}"></script>
    <script src="{% static 'js/metisMenu.min.js' %}"></script>
    <script src="{% static 'js/meanmenu.min.js' %}"></script>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/backtotop.js' %}"></script>
    <script src="{% static 'js/counterup.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/countdown.js' %}"></script>
    <script src="{% static 'js/smooth-scrollbar.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}

    <script>
      function showNotification(text, type) {
        // Close Notification Button
        const closeSVG = `<svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M8.82658 7.50016L14.7251 1.60135C15.0916 1.23517 15.0916 0.641039 14.7251 0.274865C14.3587 -0.0916217 13.7652 -0.0916217 13.3987 0.274865L7.50016 6.17367L1.60128 0.274865C1.23481 -0.0916217 0.641325 -0.0916217 0.274854 0.274865C-0.0916179 0.641039 -0.0916179 1.23517 0.274854 1.60135L6.17373 7.50016L0.274854 13.399C-0.0916179 13.7651 -0.0916179 14.3593 0.274854 14.7254C0.458089 14.9084 0.698234 15 0.938067 15C1.1779 15 1.41804 14.9084 1.60128 14.7251L7.50016 8.82633L13.3987 14.7251C13.582 14.9084 13.8221 15 14.0619 15C14.3018 15 14.5419 14.9084 14.7251 14.7251C15.0916 14.359 15.0916 13.7648 14.7251 13.3987L8.82658 7.50016Z" fill="#AEB0D7"/>
    </svg>
    `;

        // Wheather the icon is check or cross
        const checkIcon =
          type != "error"
            ? `
        <svg class="icon" width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M24.6094 12.5C24.6094 19.1878 19.1878 24.6094 12.5 24.6094C5.81216 24.6094 0.390625 19.1878 0.390625 12.5C0.390625 5.81216 5.81216 0.390625 12.5 0.390625C19.1878 0.390625 24.6094 5.81216 24.6094 12.5ZM11.0993 18.9118L20.0837 9.92744C20.3888 9.62236 20.3888 9.12769 20.0837 8.82261L18.9789 7.71777C18.6738 7.41265 18.1791 7.41265 17.874 7.71777L10.5469 15.0448L7.12603 11.624C6.82095 11.3189 6.32627 11.3189 6.02114 11.624L4.91631 12.7288C4.61123 13.0339 4.61123 13.5286 4.91631 13.8336L9.99443 18.9118C10.2996 19.2169 10.7942 19.2169 11.0993 18.9118Z" fill="#22C55E"/>
    </svg>
      `
            : `
        <svg class="icon" width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M12.5 0.390625C5.81055 0.390625 0.390625 5.81055 0.390625 12.5C0.390625 19.1895 5.81055 24.6094 12.5 24.6094C19.1895 24.6094 24.6094 19.1895 24.6094 12.5C24.6094 5.81055 19.1895 0.390625 12.5 0.390625ZM18.4375 15.6787C18.667 15.9082 18.667 16.2793 18.4375 16.5088L16.5039 18.4375C16.2744 18.667 15.9033 18.667 15.6738 18.4375L12.5 15.2344L9.32129 18.4375C9.0918 18.667 8.7207 18.667 8.49121 18.4375L6.5625 16.5039C6.33301 16.2744 6.33301 15.9033 6.5625 15.6738L9.76562 12.5L6.5625 9.32129C6.33301 9.0918 6.33301 8.7207 6.5625 8.49121L8.49609 6.55762C8.72559 6.32812 9.09668 6.32812 9.32617 6.55762L12.5 9.76562L15.6787 6.5625C15.9082 6.33301 16.2793 6.33301 16.5088 6.5625L18.4424 8.49609C18.6719 8.72559 18.6719 9.09668 18.4424 9.32617L15.2344 12.5L18.4375 15.6787Z" fill="#EF4444"/>
    </svg>
      `;

        // Notification markup
        const markup = `
        <div class="notification ${type}">
          <div class="content">
            <div class="img">${checkIcon}</div>
            <div class="text">${text}</div>
          </div>
          <div class="close">${closeSVG}</div>
          <div class="progress-bar ${type}"></div>
        </div>
      `;

        // Add notification to the page
        const notificationContainer = document.querySelector(".notifications");
        notificationContainer.insertAdjacentHTML("afterbegin", markup);

        // Remove notification when progress bar end animation
        notificationContainer.querySelectorAll(".progress-bar").forEach((item) => {
          item.addEventListener("animationend", function (e) {
            if (e.animationName == "scale-width") {
              const notification = this.closest(".notification");

              // Fadeout notification
              fadeoutNotification(notification);

              // Remove notification
              notification.ontransitionend = function (e) {
                if (e.propertyName == "opacity") {
                  removeNotification(this);
                }
              };
            }
          });
        });

        // Close the notification
        notificationContainer.addEventListener("pointerdown", (e) => {
          const target = e.target;
          if (target.classList.contains("close")) {
            const notification = target.closest(".notification");
            // Fadeout notification
            fadeoutNotification(notification);

            // Remove notification
            notification.ontransitionend = function (e) {
              if (e.propertyName == "opacity") {
                removeNotification(this);
              }
            };
          }
        });
      }

      function fadeoutNotification(notification) {
        notification.style.opacity = 0;
      }

      function removeNotification(notification) {
        notification.remove();
      }
    </script>

    {% if messages %} {% for message in messages %}
    <script>
      showNotification('{{ message|safe }}', '{{ message.tags }}')
    </script>
    {% endfor %} {% endif %}

    {% block page_js %} {% endblock %}
  </body>

  <!-- Mirrored from codeskdhaka.com/html/expovent-prev/expovent/{% url 'users:home' %} by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 17 Mar 2024 11:54:13 GMT -->
</html>

templates/create-forum.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="app__slide-wrapper">
  <div class="breadcrumb__area">
    <div class="breadcrumb__wrapper mb-35">
      <div class="breadcrumb__main">
        <div class="breadcrumb__inner">
          <div class="breadcrumb__icon">
            <i class="flaticon-home"></i>
          </div>
          <div class="breadcrumb__menu">
            <nav>
              <ul>
                <li>
                  <span><a href="{% url 'users:home' %}">Home</a></span>
                </li>
                <li class="active"><span>Create Forum</span></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xxl-12">
      <div class="create__event-area">
        <div class="body__card-wrapper">
          <div class="card__header-top">
            <div class="card__title-inner">
              <h4 class="event__information-title">Forum Information</h4>
            </div>
          </div>
          <form action="{% url 'users:create-forum' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="create__event-main pt-25">
              <div class="event__left-box">
                <div class="create__input-wrapper">
                  <div class="singel__input-field mb-15">
                    <label class="input__field-text">Forum Name</label>
                    {{ form.name }}
                    <small class="txt-danger">{{ form.name.errors }}</small> <!-- Error checking for Forum Name -->
                  </div>
                  <div class="event__input mb-15">
                    <label class="input__field-text">Forum Details</label>
                    {{ form.details }}
                    <small class="txt-danger">{{ form.details.errors }}</small> <!-- Error checking for Forum Details -->
                  </div>
                </div>
              </div>
              <div class="event__right-box">
                <div class="create__input-wrapper">
                  <div class="event__update-wrapper">
                    <div class="popup__update">
                      <label>Upload Image (200x200px)</label>
                      {{ form.image }}
                    </div>
                  </div>
                  <button class="input__btn w-100" type="submit">Add Forum</button>
                </div>
              </div>
            </div>
          </form>
          
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/jobs.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="app__slide-wrapper">
  <div class="breadcrumb__area">
    <div class="breadcrumb__wrapper mb-35">
      <div class="breadcrumb__main">
        <div class="breadcrumb__inner">
          <div class="breadcrumb__icon">
            <i class="flaticon-home"></i>
          </div>
          <div class="breadcrumb__menu">
            <nav>
              <ul>
                <li>
                  <span><a href="{% url 'users:home' %}">Home</a></span>
                </li>
                <li class="active"><span>Job Listing</span></li>
              </ul>
            </nav>
          </div>
        </div>
        <div class="breadcrum__button">
          {% if request.user.is_superuser %}
          <a class="breadcrum__btn event__popup-active" href="{% url 'users:create-event' %}">Create Job<i class="fa-regular fa-plus"></i></a>
          {% else %}
          <a class="breadcrum__btn event__popup-active" href="{% url 'users:register-event' %}">Apply Job<i class="fa-regular fa-plus"></i></a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="event__list-area pb-20">
    <div class="event__content-inner">
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="day-tab-1-pane" role="tabpanel" aria-labelledby="day-tab-1" tabindex="0">
          <div class="body__card-wrapper">
            <h4 class="event__information-title mb-25">Upcoming Event Information</h4>
            <div class="attendant__wrapper mb-35">
              <table>
                <thead>
                  <tr>
                    <th>ID No</th>
                    <th>Job Name</th>
                    <th>Company</th>
                    <th>Deadline</th>
                    <th>Location</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for job in jobs %}
                  <tr>
                    <td>
                      <div class="attendant__serial">
                        <span>#{{ job.id }}</span>
                      </div>
                    </td>
                    <td>
                      <div class="attendant__seminer">
                        <span><a href="{{ event.get_absolute_url }}">{{ job.title }}</a></span>
                      </div>
                    </td>
                    <td>
                      <div class="attendant__speakers">
                        <div class="attendant__speakers-thumb">
                          {{ job.company }}
                        </div>
                      </div>
                    </td>
                    <td>
                      <div class="attendant__date">
                        <span>{{ job.deadline|date:"d M Y" }}</span>
                      </div>
                    </td>
                    <td>
                      <div class="attendant__location">
                        <span>{{ job.location }}</span>
                      </div>
                    </td>
                    <td>
                      <div class="attendant__action">
                        <div class="card__header-dropdown">
                          <div class="dropdown">
                            <button>
                              <svg class="attendant__dot" width="14" height="4" viewBox="0 0 14 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M2 0.75C2.69036 0.75 3.25 1.30964 3.25 2C3.25 2.69036 2.69036 3.25 2 3.25C1.30964 3.25 0.75 2.69036 0.75 2C0.75 1.30964 1.30964 0.75 2 0.75Z" fill="white"></path>
                                <path d="M7 0.75C7.69036 0.75 8.25 1.30964 8.25 2C8.25 2.69036 7.69036 3.25 7 3.25C6.30964 3.25 5.75 2.69036 5.75 2C5.75 1.30964 6.30964 0.75 7 0.75Z" fill="white"></path>
                                <path d="M13.25 2C13.25 1.30964 12.6904 0.75 12 0.75C11.3096 0.75 10.75 1.30964 10.75 2C10.75 2.69036 11.3096 3.25 12 3.25C12.6904 3.25 13.25 2.69036 13.25 2Z" fill="white"></path>
                              </svg>
                            </button>
                            <div class="dropdown-list">
                              <a class="dropdown__item" href="{{ job.get_update_url }}">Apply</a>
                              <a class="dropdown__item" href="{{ job.get_delete_url }}">Bookmark</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            {% include 'includes/pagination.html' with results=jobs %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}

{% load static %}

{% block page_css %}
<style>
   .page__body-wrapper {
      width: 100%;
   }
   
   .app__header__area,
   .progress-wrap.active-progress,
   .expovent__sidebar {
      display: none !important;
   }
</style>
{% endblock %}

{% block content %}

      <!-- signin area start -->
      <section class="signin__area">
         <div class="sign__main-wrapper">
            <div class="sign__left">
               <div class="sign__header">
                  <div class="sign__logo">
                     <a href="{% url 'users:home' %}">
                        <img class="logo-black" src="{% static 'img/logo/logo-black.png' %}" alt="image not found">
                        <img class="logo-white" src="{% static 'img/logo/logo.png' %}" alt="image not found">
                     </a>
                  </div>
                  <div class="sign__link">
                     <a class="sign__link-active" href="{% url 'users:signin' %}">Sign in</a>
                     <a class="sign__link-text" href="{% url 'users:signup' %}">Sign Up</a>
                  </div>
               </div>
               <div class="sign__center-wrapper text-center mt-90">
                  <div class="sign__title-wrapper mb-40">
                     <h3 class="sign__title">Welcome To EventMS</h3>
                     <p>The faster you fill up. the faster you get a ticket</p>
                  </div>
                  <div class="sign__input-form text-center">
                     <form action="{% url 'users:signin' %}" method="post">
                        {% csrf_token %}
                        <div class="sign__input">
                           {{ form.email }}
                           {% for error in form.email.errors %}
                              <p class="error-message">{{ error }}</p>
                           {% endfor %}
                           <span><i class="flaticon-user-2"></i></span>
                        </div>
                        <div class="sign__input">
                           {{ form.password }}
                           {% for error in form.password.errors %}
                              <p class="error-message">{{ error }}</p>
                           {% endfor %}
                           <span><i class="flaticon-password"></i></span>
                        </div>
                        <div class="sign__action">
                           <div class="sign__check">
                              <input class="e-check-input" type="checkbox" id="register">
                              <label class="sign__check-text" for="register"><span>Remember Me</span></label>
                           </div>
                           <div class="sign__forget">
                              <span><a href="{% url 'password_reset' %}">Forgot Password?</a></span>
                           </div>
                        </div>
                        <div class="sing__button mb-20">
                           <button class="input__btn w-100 mb-20" type="submit">Sign in</button>
                           
                        </div>
                     </form>
                     <div class="if__account mt-85">
                        <p>Don’t Have An Account?<a href="{% url 'users:signup' %}"> Sign up</a></p>
                     </div>
                  </div>
               </div>
            </div>
            <div class="sign__right">
               <div class="sign__input-thumb" data-background="{% static 'img/sign/signin.jpg' %}">
               </div>
            </div>
         </div>
      </section>
      <!-- signin area end -->
   
   {% endblock %}

templates/signup.html
{% extends 'base.html' %} {% load static %} 

{% block page_css %}
<style>
   .page__body-wrapper {
      width: 100%;
   }
   
   .app__header__area,
   .progress-wrap.active-progress,
   .expovent__sidebar {
      display: none !important;
   }
</style>
{% endblock %}

{% block content %}


<!-- signup area start -->
<section class="signin__area">
  <div class="sign__main-wrapper">
    <div class="sign__left">
      <div class="sign__header">
        <div class="sign__logo">
          <a href="{% url 'users:home' %}">
            <img class="logo-black" src="{% static 'img/logo/logo-black.png' %}" alt="image not found">
            <img class="logo-white" src="{% static 'img/logo/logo.png' %}" alt="image not found">
          </a>
        </div>
        <div class="sign__link">
          <a class="sign__link-text" href="{% url 'users:signin' %}">Sign in</a>
          <a class="sign__link-active" href="{% url 'users:signup' %}">Sign Up</a>
        </div>
      </div>
      <div class="sign__center-wrapper text-center mt-80">
        <div class="sign__title-wrapper mb-40">
          <h3 class="sign__title">Create An Account</h3>
          <p>The faster you fill up. the faster you get a ticket</p>
        </div>
        <div class="sign__input-form text-center">
          <form action="{% url 'users:signup' %}" method="post">
            {% csrf_token %}
            <div class="sign__input">
               {{ form.name }}
               {% for error in form.name.errors %}
                 <p class="error-message">{{ error }}</p>
               {% endfor %}
              <span><i class="flaticon-user-2"></i></span>
            </div>
            <div class="sign__input">
              {{ form.email }}
               {% for error in form.email.errors %}
                   <p class="error-message">{{ error }}</p>
                {% endfor %}
              <span><i class="flaticon-user-2"></i></span>
            </div>
            <div class="sign__input">
              {{ form.password1 }}
               {% for error in form.password1.errors %}
                   <p class="error-message">{{ error }}</p>
                {% endfor %}
              <span><i class="flaticon-password"></i></span>
            </div>
            <div class="sign__input">
              {{ form.password2 }}
               {% for error in form.password2.errors %}
                   <p class="error-message">{{ error }}</p>
                {% endfor %}
              <span><i class="flaticon-password"></i></span>
            </div>
            <div class="sing__button mb-20">
              <button class="input__btn w-100 mb-20" type="submit">Sign Up</button>
            </div>
          </form>
          <div class="if__account mt-90">
            <p>Already have an account? <a href="{% url 'users:signin' %}">Sign in</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="sign__right">
      <div class="sign__input-thumb include__bg w-img" data-background="{% static 'img/sign/signup.jpg' %}"></div>
    </div>
  </div>
</section>
<!-- Signup area start -->

{% endblock %}